import type { Metadata } from "next";
import "./globals.css";
import { MyContextProvider } from "./Redux/Store";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <MyContextProvider>
        <body className="font-['quicksand'] background">{children}</body>
      </MyContextProvider>
    </html>
  );
}
