
###
POST http://localhost:5000/api/access/register
Content-Type: application/json

{
 "firstname": "gabby",
  "lastname" : "cruz",
  "email":"cruz@gmail.com",
  "password": "cruz@"
}


###
POST http://localhost:5000/api/access/login
Content-Type: application/json

{
  "email": "cruz@gmail.com",
  "password" : "T56e44dfghjkl@"
}


###
POST http://localhost:5000/api/access/verify_email
Content-Type: application/json

{
  "email":"cruz@gmail.com"
}

###
POST http://localhost:5000/api/access/verify_otp
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNydXpAZ21haWwuY29tIiwiaWF0IjoxNzIzNTc3OTIwLCJleHAiOjE3MjM1Nzc5ODB9.SJA_Zxc3YKyjKgMqppqcB4BjKuzn1iRFsV3MWz1ieYU

{
  "otp_code":"3220"
}

###
POST http://localhost:5000/api/access/reset_password
Content-Type: application/json

{
   "password": "T56e44dfghjkl@",
   "email": "cruz@gmail.com"
}

###
Get http://localhost:5000/api/access/home
Content-Type: application/json
x-auth-token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VsbGxAZ21haWwuY29tIiwiaWF0IjoxNzA3MjQyMzM3LCJleHAiOjE3MDcyNDIzOTd9.JdJ05EvNwYPkiNb6pxM8LELyVc2TmFA1XiJjlGR8Q-s"

###
POST  http://localhost:5000/api/organizer/create_event
Content-Type: application/json

{
  "organizerID": "23",
  "email": "cruz@gmail.com",
  "EventName": "school night",
  "location": "eko hotel, lekki phase 1 lagos, Nigeria",
  "description" : "Night of flexing",
  "EventDate": "11 August 2024",
  "StartTime" : "11:00pm",
  "EndTime" : "Till Dawn (6:00am)"
}

###
POST  http://localhost:5000/
Content-Type: application/json

{
  "profilePictureUrl": "https://linkedin.com/in/user123",
  "profileName": "Gabby Soft",
  "bio": "LinkedIn",
  "socailHandle": [],
  "links": [
    {
      "title": "My Blog",
      "url": "https://myblog.com"
    },
    {
      "title": "LinkedIn",
      "url": "https://linkedin.com/in/user123"
    }
  ],
   "supportDetails" : [
      {
      "title": "My Blog",
      "url": "https://myblog.com"
    },
    {
      "title": "LinkedIn",
      "url": "https://linkedin.com/in/user123"
    }
   ]
}

###
POST  http://localhost:5000/temp
Content-Type: application/json

{
 "email" : "gabbysoft2002@gmail.com"
}
